"""empty message

Revision ID: 5b65a615d36d
Revises: 92a36e8fafd0
Create Date: 2026-09-19 01:28:00.141312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b65a615d36d'
down_revision = '92a36e8fafd0'
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.create_unique_constraint('email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('email', type_='unique')
        batch_op.drop_column('email')


    # ### end Alembic commands ###
